title: Madhumithaa | Portfolio
email: madhumithaa1411@gmail.com
author: Madhumithaa
description: A sassy woman, with crazy passion to develop applications.
about: >
    Loves experimenting with code, teamwork and challenging opportunities.
    Has good knowledge in HTML, CSS and JavaScript. Currently learning React.
    Definitely can’t write my own code, I mostly copy & paste. But ya, "Every Boss Started As A Worker".
    I am definitely not the best, but try me!!!
simpleform_url: "https://getsimpleform.com/messages?form_api_token=99de8832756f8b978ef637a1c0add178"
baseurl: ""
url: ""
markdown: kramdown
theme: minima
plugins:
    - jekyll-feed
    - jekyll-gzip
# TODO: sitemap.xml
# TODO: google analytics
# TODO: Resume
